### ISSUE TITLE
Links for Containers/OpenShift/Satellite point to Logging not Metrics

### ISSUE THREAD

**Issue by rjminsha** [ibm-cloud-docs/monitoring#1]
https://cloud.ibm.com/docs/containers?topic=containers-health#sysdig 
https://cloud.ibm.com/docs/openshift?topic=openshift-health#openshift_sysdig
https://cloud.ibm.com/docs/satellite?topic=satellite-health#setup-sysdig

While the URLs look relevant the page content is all about Logging not Metrics

**Comment by artberger** [comment]
@rjminsha those links were changed (and also to remove the word Sysdig)...the new links are:
* https://cloud.ibm.com/docs/containers?topic=containers-health-monitor#monitoring
* https://cloud.ibm.com/docs/openshift?topic=openshift-health-monitor#openshift_monitoring
* https://cloud.ibm.com/docs/satellite?topic=satellite-monitor#setup-mon
