### ISSUE TITLE
The retention statement for the granularity should be 2 months

### ISSUE THREAD

**Issue by JohnPaulParkin** [ibm-cloud-docs/monitoring#12]
There's a statement in the  https://cloud.ibm.com/docs/monitoring?topic=monitoring-mng-data page that has the following text : 

`As time progresses, the data is rolled up from a fine granularity to a coarser one by the end 3 months.`

The 3 months should be changed to 2 months in order to match the data retention in the bullets.

**Comment by vanadiscrawford** [comment]
Thank you for your comment.  The information has been corrected and will be seen after the next documentation update.
