### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tsulliva333** [ibm-cloud-docs/monitoring#4]
At the bottom of the [Monitoring a Kubernetes cluster](https://cloud.ibm.com/docs/monitoring?topic=monitoring-kubernetes_cluster) page, within the **Next Steps** section, the sentence `Create a custom dashboard. For more information, see Working with dashboards.` contains the following broken link: https://cloud.ibm.com/docs/monitoring?topic=monitoring-dashboards#dashboards

**Comment by vanadiscrawford** [comment]
Thank you for your comment!  The issue has been resolved.
