### ISSUE TITLE
Broken links on Monitoring Cloud Foundry metrics -> Viewing Metrics

### ISSUE THREAD

**Issue by ebcarty** [ibm-cloud-docs/monitoring#5]
There are two broken links under "[Viewing Metrics](https://cloud.ibm.com/docs/monitoring?topic=monitoring-monitor-cf-sysdig#view_metrics)" section...

1. Copy the pre-defined dashboard (https://cloud.ibm.com/docs/monitoring?topic=monitoring-dashboards#dashboards_copy)
2. Change the scope of the new dashboard (https://cloud.ibm.com/docs/monitoring?topic=monitoring-dashboards#dashboards_scope)

![image](https://user-images.githubusercontent.com/13952816/117202671-f1532f80-ada2-11eb-8d40-2e5d92c9c6f1.png)

**Comment by vanadiscrawford** [comment]
Thank you for bringing this to our attention.  This issue has been resolved and the links are working correctly.
