### ISSUE TITLE
`curl | sudo bash` in examples

### ISSUE THREAD

**Issue by inahga** [ibm-cloud-docs/monitoring#6]
We noticed in these docs that it's suggested to use the `curl | sudo bash` pattern to install the sysdig agent.
- https://cloud.ibm.com/docs/monitoring?topic=monitoring-baremetal_linux
- https://cloud.ibm.com/docs/monitoring?topic=monitoring-ubuntu#ubuntu_step3

The exact command:
```
curl -sL https://ibm.biz/install-sysdig-agent | sudo bash -s -- --access_key ACCESS_KEY --collector COLLECTOR_ENDPOINT --collector_port 6443 --secure false --tags TAG_DATA --additional_conf 'sysdig_capture_enabled: false'
```

This pattern is risky since it's executing an arbitrary shell script as root on the target machine, so its use should be discouraged. This pattern was the vector for the recent codecov attacks. This script seems especially risky since it's on an AWS S3 bucket, which I assume is totally out of IBM control.

I noticed the script does install an `apt` repository, so I suggest those sections to be rewritten to suggest installing the sysdig `apt` repository and writing a configuration file.

**Comment by lopezdsr** [comment]
Thank you very much for your feedback. We will review.
