### ISSUE TITLE
Missing jg dependency when setting up kubernetes monitoring

### ISSUE THREAD

**Issue by EdrianI** [ibm-cloud-docs/monitoring#7]
Hi, 

Following your instructions works up to a certain point. On Step 2, sub-step 5, there is a long command that a user is expected to enter. The command executes to a certain point, it fails if you do not have the **jg** package installed on your machine.

The command causing the problem

>  curl -sL https://raw.githubusercontent.com/draios/sysdig-cloud-scripts/master/agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh | bash -s -- -a ACCESS_KEY -c COLLECTOR_ENDPOINT -t TAG_DATA -ac 'sysdig_capture_enabled: false'

A snippet of error  after running the command

> secret/sysdig-agent created
> * Retreiving the IKS Cluster ID and Cluster Name
> * Setting cluster name as cfc-us-south-3-bx2.2x8/c0i18r6d09hm2v8tstb0
> * Setting ibm.containers-kubernetes.cluster.id c0i18r6d09hm2v8tstb0
> * Updating agent configmap and applying to cluster
> * Setting tags
> * Setting collector endpoint
> * Adding additional configuration to dragent.yaml
> * Enabling Prometheus
> Slim agent selected 
> Processing all-icr-io as all-icr-io
> bash: line 354: jq: command not found
> error: no objects passed to apply

 Notice on the second to the last line, there is a **command not found** failure. After installing the jg package using the brew package manager, executing the same command completes and works as intended.

Link to Step 2 : https://cloud.ibm.com/docs/monitoring?topic=monitoring-kubernetes_cluster#kubernetes_cluster_step2

**Comment by lopezdsr** [comment]
Thank you very much for your feedback. We will update the instructions.
