### ISSUE TITLE
Link to Working with image scanning is broken

### ISSUE THREAD

**Issue by EdrianI** [ibm-cloud-docs/monitoring#8]
When I click on the link highlighted below, it takes me to a Sysdig says page not found

![Screen Shot 2021-05-18 at 4 10 57 PM](https://user-images.githubusercontent.com/7958452/118717192-bcf46000-b7f3-11eb-98a1-a4dda8f5d3e5.png)

**Comment by vanadiscrawford** [comment]
Thank you for bringing this to our attention.  We are fixing the link and the update will be seen in the next published update.
