### ISSUE TITLE
Invalid Pricing Plan ID link

### ISSUE THREAD

**Issue by thomascheuk** [ibm-cloud-docs/monitoring#9]
One the pricing page, In first table under the section "The following service plans are available:" It shows a column called "Plan ID" with some random numbers.

**Comment by vanadiscrawford** [comment]
Thank you for your comment.  However, that column does not contain random numbers.  It includes the actual Plan ID value that is returned by running the following command for the instance:

```
ic resource service-instance <INSTANCE_NAME> --output JSON
```

The value is returned in the `resource_plan_id`.  For example:

```
"resource_plan_id": "231bb072-1b2f-4d7e-ae9e-9574d382be32",
```
